### ISSUE TITLE
fsdev - filesystem devices

### ISSUE THREAD

**Issue by benlwalker** [spdk/spdk.github.io#17]

**Comment by tomzawadzki** [comment]
[30min]

**Comment by tomzawadzki** [comment]
@anton-nayshtut has given a presentation on the fsdev that is now in review. 

Discussed how to perform system level testing, either using QEMU or at least passing fuse command directly to the virtio fs target.



@anton-nayshtut can you please attach the slides ?

**Comment by anton-nayshtut** [comment]
@tomzawadzki sure! :-) Here you are.

[SPDK-fsdev-for-community.pdf](https://github.com/user-attachments/files/16012794/SPDK-fsdev-for-community.pdf)
