### ISSUE TITLE
accel framework extensions (t10 dif/dix) and memory domain extensions (dma function pointer)

### ISSUE THREAD

**Issue by benlwalker** [spdk/spdk.github.io#18]

**Comment by tomzawadzki** [comment]
[30min]

**Comment by tomzawadzki** [comment]
@AlekseyMarchuk has given a presentation on the intended changes to accel framework to support the UMR, along with idea to pass the qpair pointer across target/initiator/accel.

@AlekseyMarchuk Could you please attach the presentation to this issue ?

**Comment by AlekseyMarchuk** [comment]
[mem_domain_extensions.pptx](https://github.com/user-attachments/files/15967664/mem_domain_extensions.pptx)
Please note that the provided interfaces are drafts and might be changed
