### ISSUE TITLE
CSAL/FTL theory of operation

### ISSUE THREAD

**Issue by mmkayPL** [spdk/spdk.github.io#21]
Presentation of the high level architecture of FTL, key structures and concepts, IO path flows.

**Comment by tomzawadzki** [comment]
[30min]

**Comment by tomzawadzki** [comment]
@mmkayPL has given a presentation of the  CSAL/FTL architecture. Detailing the changes currently in review for using non-vss cache devices. Introduced the idea of the CSAL append cache, that is being worked on.

@mmkayPL could you please attach slides to this issue ?

**Comment by mmkayPL** [comment]
Yesterday's presentation

[CSAL theory of operation - SPDK.pptx](https://github.com/user-attachments/files/15966449/CSAL.theory.of.operation.-.SPDK.pptx)
