### ISSUE TITLE
Devmem TCP

### ISSUE THREAD

**Issue by jkalwas** [spdk/spdk.github.io#23]
Devmem TCP is a feature developed by Google and already deployed in their production, based on their own and Meta patches, with a strong driving force to merge into the Linux kernel by the end of 2024. SPDK could leverage this approach to achieve zero-copy TCP receive flows.
 
Blog post  https://www.linkedin.com/pulse/devmem-tcp-back-future-rakesh-cheerla-buplc
Slides:
https://netdevconf.info/0x17/sessions/talk/device-memory-tcp.html  Devmem TCP
https://netdevconf.info/0x17/docs/netdev-0x17-paper24-talk-slides/Zero%20Copy%20Rx%20with%20io_uring%20-%20NetDev%20Conf%202023-1.pdf Zero copy network RX using io_uring
Patches:
https://patchwork.kernel.org/project/linux-media/list/?series=861412&state=%2A&archive=both Device memory TCP kernel patch series
https://patchwork.kernel.org/project/io-uring/list/?series=834772&state=%2A&archive=both Zero copy Rx using io_uring kernel patch series
https://github.com/spikeh/linux/tree/zcrx/next Devmem TCP + Zero copy
https://github.com/spikeh/liburing/tree/zcrx/next liburing
https://github.com/spikeh/netbench/tree/zcrx/next Benchmarking tool
 
Same topic SPDK patch series:
https://review.spdk.io/gerrit/c/spdk/spdk/+/17597/28

**Comment by tomzawadzki** [comment]
[30min]

**Comment by jimharris** [comment]
Need to track work on this. No immediate takeaways.
