### ISSUE TITLE
bdev performance issues (struct layouts impact performance in unpredictable ways)

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk.github.io#27]
@benlwalker - as part of this topic, could you talk about any of the stacked bdev improvements you have been prototyping? I feel like this is an important consideration for this topic - i.e. does accepting a 4-5% degradation based on random performance impacts enable a much bigger improvement for stacked bdevs or other optimizations?

**Comment by ksztyber** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/21938
https://review.spdk.io/gerrit/c/spdk/spdk/+/21937
