### ISSUE TITLE
partial polling

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk.github.io#31]

**Comment by tomzawadzki** [comment]
[30min]

**Comment by tmakatos** [comment]
For virtual NVMe (nvmf/vfio-user), SPDK mapping the memory of all VMs can be a security problem. Havin an individual SPDK process per VM solves the security problem but that SPDK process has to run in interrupt mode. A middle could be to have a single, dedicated SPDK process do the polling and notify the per-VM SPDK process to do the processing. The single, dedicated SPDK process only has to map the doorbells of all vNVMe devices.
